In [92]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [131]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('float_format', '{:.10f}'.format)

In [132]:
path = "/content/drive/MyDrive/광진구 빅데이터 공모전/화상투약기_입지선정/데이터/버스 데이터/"

In [207]:
bus = pd.read_csv(path + "kwangjin_bus_night.csv").drop(['Unnamed: 0.1', 'Unnamed: 0', '행정구'], axis=1)
bus.head()

,버스정류장ARS번호,승차총승객수,하차총승객수,X좌표,Y좌표,정류소명,행정동,18시승차총승객수,18시하차총승객수,19시승차총승객수,19시하차총승객수,20시승차총승객수,20시하차총승객수,21시승차총승객수,21시하차총승객수,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,00시승차총승객수,00시하차총승객수,1시승차총승객수,1시하차총승객수,2시승차총승객수,2시하차총승객수,3시승차총승객수,3시하차총승객수,4시승차총승객수,4시하차총승객수,5시승차총승객수,5시하차총승객수,6시승차총승객수,6시하차총승객수
0,5001,549811,473277,127.0756403407,37.5587315243,군자교입구,중곡동,37325,38590,28790,30838,20188,21680,20325,22903,16595,22765,9850,13873,5093,5778,1524,3322,628,805,988,1105,6693,3009,12566,7155,19700,10167
1,5001,549811,473277,127.0756403407,37.5587315243,군자교입구,중곡동,444,665,260,683,198,370,160,466,206,509,161,445,83,302,45,82,0,0,0,0,0,0,0,0,0,0
2,5002,408745,543539,127.0748828032,37.5587645852,군자교입구,군자동,27937,59793,21511,41798,14169,26721,13241,26353,12510,23183,8347,14400,4660,7708,1029,2487,448,1608,139,782,652,1400,13056,16744,13359,11917
3,5002,408745,543539,127.0748828032,37.5587645852,군자교입구,군자동,5779,190,3844,86,2152,69,1302,67,850,55,310,46,11,0,0,0,0,0,0,0,0,0,45,1,307,35
4,5003,475101,486287,127.0824524600,37.5560651252,군자역4번출구.용마초등학교,중곡동,38161,42079,26030,30444,21107,22740,23482,22754,18861,19319,10062,11676,4986,5983,1282,5545,629,1859,913,2566,7337,3096,10931,12633,12723,10901

In [155]:
bus['X좌표'][0]

127.0756403407

In [156]:
bus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   버스정류장ARS번호  274 non-null    int64
 1   승차총승객수      274 non-null    int64
 2   하차총승객수      274 non-null    int64
 3   X좌표         274 non-null    float64
 4   Y좌표         274 non-null    float64
 5   정류소명        274 non-null    object
 6   행정구         274 non-null    object
 7   행정동         274 non-null    object
 8   18시승차총승객수   274 non-null    int64
 9   18시하차총승객수   274 non-null    int64
 10  19시승차총승객수   274 non-null    int64
 11  19시하차총승객수   274 non-null    int64
 12  20시승차총승객수   274 non-null    int64
 13  20시하차총승객수   274 non-null    int64
 14  21시승차총승객수   274 non-null    int64
 15  21시하차총승객수   274 non-null    int64
 16  22시승차총승객수   274 non-null    int64
 17  22시하차총승객수   274 non-null    int64
 18  23시승차총승객수   274 non-null    int64
 19  23시하차총승객수   274 non-null    int64
 20  00시승차총승객수   274 non-null    int64
 21  00시하차총승객수   274 non-null    int64
 22  1시승차총승객수    274 non-null    int64
 23  1시하차총승객수    274 non-null    int64
 24  2시승차총승객수    274 non-null    int64
 25  2시하차총승객수    274 non-null    int64
 26  3시승차총승객수    274 non-null    int64
 27  3시하차총승객수    274 non-null    int64
 28  4시승차총승객수    274 non-null    int64
 29  4시하차총승객수    274 non-null    int64
 30  5시승차총승객수    274 non-null    int64
 31  5시하차총승객수    274 non-null    int64
 32  6시승차총승객수    274 non-null    int64
 33  6시하차총승객수    274 non-null    int64
dtypes: float64(2), int64(29), object(3)
memory usage: 72.9+ KB

In [158]:
bus_temp = bus[['X좌표', 'Y좌표', '정류소명', '승차총승객수', '하차총승객수', '18시승차총승객수', '18시하차총승객수', '19시승차총승객수', '19시하차총승객수', 
                '20시승차총승객수', '20시하차총승객수', '21시승차총승객수', '21시하차총승객수', '22시승차총승객수', '22시하차총승객수', '23시승차총승객수', 
                '23시하차총승객수', '00시승차총승객수','00시하차총승객수', '1시승차총승객수', '1시하차총승객수', '2시승차총승객수', '2시하차총승객수', '3시승차총승객수',
                '3시하차총승객수', '4시승차총승객수', '4시하차총승객수', '5시승차총승객수', '5시하차총승객수', '6시승차총승객수', '6시하차총승객수']]

bus_temp = bus_temp.groupby('정류소명').agg({'승차총승객수': 'sum', '하차총승객수': 'sum', '18시승차총승객수': 'sum', '18시하차총승객수': 'sum', '19시승차총승객수': 'sum', 
                                         '19시하차총승객수': 'sum', '20시승차총승객수': 'sum', '20시하차총승객수': 'sum', '21시승차총승객수': 'sum', '21시하차총승객수': 'sum', 
                                         '22시승차총승객수': 'sum', '22시하차총승객수': 'sum', '23시승차총승객수': 'sum', '23시하차총승객수': 'sum', '00시승차총승객수': 'sum',
                                         '00시하차총승객수': 'sum', '1시승차총승객수': 'sum', '1시하차총승객수': 'sum', '2시승차총승객수': 'sum', '2시하차총승객수': 'sum', 
                                         '3시승차총승객수': 'sum', '3시하차총승객수': 'sum', '4시승차총승객수': 'sum', '4시하차총승객수': 'sum', '5시승차총승객수': 'sum', 
                                         '5시하차총승객수': 'sum', '6시승차총승객수': 'sum', '6시하차총승객수': 'sum'}).reset_index()

In [160]:
bus_temp2 = bus[['정류소명', 'X좌표', 'Y좌표']]
bus_temp2[['X좌표', 'Y좌표']].astype('float')
bus_temp2 = bus_temp2.drop_duplicates(subset=['정류소명'], keep='first')
busfinal = pd.merge(bus_temp2, bus_temp, on='정류소명')
busfinal.head()

,정류소명,X좌표,Y좌표,승차총승객수,하차총승객수,18시승차총승객수,18시하차총승객수,19시승차총승객수,19시하차총승객수,20시승차총승객수,20시하차총승객수,21시승차총승객수,21시하차총승객수,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,00시승차총승객수,00시하차총승객수,1시승차총승객수,1시하차총승객수,2시승차총승객수,2시하차총승객수,3시승차총승객수,3시하차총승객수,4시승차총승객수,4시하차총승객수,5시승차총승객수,5시하차총승객수,6시승차총승객수,6시하차총승객수
0,군자교입구,127.0756403407,37.5587315243,1917112,2033632,71485,99238,54405,73405,36707,48840,35028,49789,30161,46512,18668,28764,9847,13788,2598,5891,1076,2413,1127,1887,7345,4409,25667,23900,33366,22119
1,군자역4번출구.용마초등학교,127.0824524600,37.5560651252,950202,972574,38167,42473,26032,30785,21112,22905,23489,22922,18861,19453,10067,11798,4989,6069,1285,5574,629,1859,913,2566,7337,3096,10931,12633,12723,10901
2,군자역5번출구.용마초등학교,127.0815389967,37.5561793641,1339456,1097230,53879,52474,42845,39657,33614,26442,38891,24338,30919,20567,20667,12356,16477,6427,4160,2064,2749,1374,1577,535,6794,3400,17919,13216,17910,12420
3,중곡동입구삼거리,127.0865474987,37.5544916304,552117,709854,37506,67650,23821,47154,15908,32729,15241,32964,13067,28118,7499,16505,2804,7371,455,3022,441,1380,483,1187,6925,5872,15145,19973,20923,16029
4,어린이대공원후문아차산역,127.0902385392,37.5512477746,2157513,2080429,108750,135298,87884,99256,70241,70288,63203,66186,52748,57629,29210,31410,11544,17094,3275,4485,1292,1524,955,949,21901,4682,42850,24566,52310,36696

In [209]:
add_range = [i for i in range(18, 24)] + [i for i in range(0, 7)]
add_range

[18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6]

In [ ]:
busfinal = busfinal.rename(columns={'00시승차총승객수':'0시승차총승객수', '00시하차총승객수':'0시하차총승객수'})
for i in add_range:
    busfinal[f'{str(i)}시_버스_승하차승객수'] = busfinal[f'{str(i)}시승차총승객수'] + busfinal[f'{str(i)}시하차총승객수']

busfinal = busfinal.rename(columns={'X좌표': "정류장X좌표", "Y좌표": "정류장Y좌표"})
busfinal.head()

In [212]:
busfinal = busfinal.drop(['18시승차총승객수', '18시하차총승객수', '19시승차총승객수', '19시하차총승객수', '20시승차총승객수',
       '20시하차총승객수', '21시승차총승객수', '21시하차총승객수', '22시승차총승객수', '22시하차총승객수',
       '23시승차총승객수', '23시하차총승객수', '0시승차총승객수', '0시하차총승객수', '1시승차총승객수',
       '1시하차총승객수', '2시승차총승객수', '2시하차총승객수', '3시승차총승객수', '3시하차총승객수', '4시승차총승객수',
       '4시하차총승객수', '5시승차총승객수', '5시하차총승객수', '6시승차총승객수', '6시하차총승객수',], axis=1)
busfinal.head(2)

,정류소명,정류장X좌표,정류장Y좌표,승차총승객수,하차총승객수,18시_버스_승하차승객수,19시_버스_승하차승객수,20시_버스_승하차승객수,21시_버스_승하차승객수,22시_버스_승하차승객수,23시_버스_승하차승객수,0시_버스_승하차승객수,1시_버스_승하차승객수,2시_버스_승하차승객수,3시_버스_승하차승객수,4시_버스_승하차승객수,5시_버스_승하차승객수,6시_버스_승하차승객수
0,군자교입구,127.0756403407,37.5587315243,1917112,2033632,170723,127810,85547,84817,76673,47432,23635,8489,3489,3014,11754,49567,55485
1,군자역4번출구.용마초등학교,127.0824524600,37.5560651252,950202,972574,80640,56817,44017,46411,38314,21865,11058,6859,2488,3479,10433,23564,23624

In [214]:
busfinal.to_csv(path+"bus_final.csv")

In [ ]:
bus_temp2 = bus[['정류소명', 'X좌표', 'Y좌표']]
bus_temp2[['X좌표', 'Y좌표']].astype('float')
bus_temp2 = bus_temp2.drop_duplicates(subset=['정류소명'], keep='first')
busfinal = pd.merge(bus_temp2, bus_temp, on='정류소명')
busfinal.head()

In [161]:
pharm = pd.read_excel(path + '광진구_약국_행정동별_경도위도.xlsx', index_col=0)
pharm = pharm.reset_index()
pharm.head()

,약국명,도로명주소,행정동,X좌표,Y좌표
0,더참사랑약국,"서울특별시 광진구 아차산로 361, 1층 (자양동)",자양1동,127.0828825135,37.5369583301
1,세계로온누리약국,"서울특별시 광진구 아차산로 219, 삼영빌딩 1층 (화양동)",화양동,127.0679320951,37.5411260816
2,튼튼약국,"서울특별시 광진구 뚝섬로 590, 아주빌딩 1층 (자양동)",자양3동,127.0753012099,37.5331352364
3,미소온누리약국,"서울특별시 광진구 아차산로 373, 원이빌딩 1층 (구의동)",구의1동,127.0840326964,37.5370119376
4,참약사도담약국,"서울특별시 광진구 아차산로 208, 상록빌딩 1층 일부호 (자양동)",자양4동,127.0664892401,37.5410609497

In [140]:
pharm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   약국명     160 non-null    object
 1   도로명주소   160 non-null    object
 2   행정동     160 non-null    object
 3   X좌표     160 non-null    float64
 4   Y좌표     160 non-null    float64
dtypes: float64(2), object(3)
memory usage: 6.4+ KB

In [141]:
##거리 계산을 위한 모듈
%pip install haversine

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: haversine in /usr/local/lib/python3.10/dist-packages (2.8.0)

In [142]:
##거리 계산을 위한 모듈 가져오기
from haversine import haversine

In [162]:
min_lst=[]
for i in range(len(pharm)):
    busstop_name=pharm.iloc[i]['약국명']
    busstop=(pharm.iloc[i]['Y좌표'],pharm.iloc[i]['X좌표'])
    min_d=10000000
    #busstop_goo=busline.iloc[i]['행정구']
    
    for j in range(len(busfinal)):
        df=busfinal.iloc[j]
        sub_name=df['정류소명']
        sub=(df['Y좌표'],df['X좌표'])
        distance=haversine(busstop, sub, unit = 'm')
        
        if min_d>distance:
            min_d=distance
            min_sub_name=sub_name
    
    min_dic={
        '약국명':busstop_name,
        '최소 거리 버스정류소': min_sub_name,
        '정류소 최소 거리':min_d
    }
    #print(min_dic)
    #print(dong_name,min_wel_name,min_d)
    min_lst.append(min_dic)

In [163]:
# sub_pharm = pd.DataFrame(min_lst)
pd.DataFrame(min_lst)

In [ ]:
pd.DataFrame(min_lst).to_csv(path + '버스_최소_거리.csv')

In [ ]:
sub_pharm = pd.read_csv(path + '버스_최소_거리.csv',index_col=0)
sub_pharm

          약국명 최소 거리 버스정류소   정류소 최소 거리
0      더참사랑약국       자양사거리   29.568379
1    세계로온누리약국       건대입구역   38.433647
2        튼튼약국     제일은행사거리   65.750847
3     미소온누리약국     구의역4번출구   74.881604
4     참약사도담약국       건대입구역   76.107375
..        ...         ...         ...
155   구의온누리약국     아차산역사거리   27.059387
156    자양건강약국     성자초등학교앞  236.435331
157       고약국         구의역   39.818597
158      진영약국      그랜드마트앞   86.493094
159    올오케이약국        새밭교회   92.446868

[160 rows x 3 columns]

In [164]:
sub_pharm = sub_pharm.rename(columns={'최소 거리 버스정류소':'정류소명', '정류소 최소 거리': '최소거리'})
sub_pharm.head()

        약국명     정류소명          최소거리
0    더참사랑약국    자양사거리 29.5683790930
1  세계로온누리약국    건대입구역 56.3272576100
2      튼튼약국  제일은행사거리 65.7508465351
3   미소온누리약국  구의역4번출구 74.8816044462
4   참약사도담약국    건대입구역 76.1073747183

In [147]:
bus.columns

Index(['버스정류장ARS번호', '승차총승객수', '하차총승객수', 'X좌표', 'Y좌표', '정류소명', '행정구', '행정동',
       '22시승차총승객수', '22시하차총승객수', '23시승차총승객수', '23시하차총승객수', '00시승차총승객수',
       '00시하차총승객수', '1시승차총승객수', '1시하차총승객수', '2시승차총승객수', '2시하차총승객수', '3시승차총승객수',
       '3시하차총승객수', '4시승차총승객수', '4시하차총승객수'],
      dtype='object')

In [197]:
new = pd.merge(sub_pharm, busfinal, on='정류소명')
new.head()

,약국명,정류소명,최소거리,X좌표,Y좌표,승차총승객수,하차총승객수,18시승차총승객수,18시하차총승객수,19시승차총승객수,19시하차총승객수,20시승차총승객수,20시하차총승객수,21시승차총승객수,21시하차총승객수,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,00시승차총승객수,00시하차총승객수,1시승차총승객수,1시하차총승객수,2시승차총승객수,2시하차총승객수,3시승차총승객수,3시하차총승객수,4시승차총승객수,4시하차총승객수,5시승차총승객수,5시하차총승객수,6시승차총승객수,6시하차총승객수
0,더참사랑약국,자양사거리,29.5683790930,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
1,조은우리약국,자양사거리,77.9440500040,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
2,행복한약국,자양사거리,146.3385579894,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
3,금성약국,자양사거리,133.0019102985,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
4,수약국,자양사거리,87.2256782004,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881

In [198]:
new.columns

Index(['약국명', '정류소명', '최소거리', 'X좌표', 'Y좌표', '승차총승객수', '하차총승객수', '18시승차총승객수',
       '18시하차총승객수', '19시승차총승객수', '19시하차총승객수', '20시승차총승객수', '20시하차총승객수',
       '21시승차총승객수', '21시하차총승객수', '22시승차총승객수', '22시하차총승객수', '23시승차총승객수',
       '23시하차총승객수', '00시승차총승객수', '00시하차총승객수', '1시승차총승객수', '1시하차총승객수',
       '2시승차총승객수', '2시하차총승객수', '3시승차총승객수', '3시하차총승객수', '4시승차총승객수', '4시하차총승객수',
       '5시승차총승객수', '5시하차총승객수', '6시승차총승객수', '6시하차총승객수'],
      dtype='object')

In [199]:
add_range = [i for i in range(18, 24)] + [i for i in range(0, 7)]
add_range

[18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6]

In [200]:
new = new.rename(columns={'00시승차총승객수':'0시승차총승객수', '00시하차총승객수':'0시하차총승객수'})
new.head()

,약국명,정류소명,최소거리,X좌표,Y좌표,승차총승객수,하차총승객수,18시승차총승객수,18시하차총승객수,19시승차총승객수,19시하차총승객수,20시승차총승객수,20시하차총승객수,21시승차총승객수,21시하차총승객수,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,0시승차총승객수,0시하차총승객수,1시승차총승객수,1시하차총승객수,2시승차총승객수,2시하차총승객수,3시승차총승객수,3시하차총승객수,4시승차총승객수,4시하차총승객수,5시승차총승객수,5시하차총승객수,6시승차총승객수,6시하차총승객수
0,더참사랑약국,자양사거리,29.5683790930,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
1,조은우리약국,자양사거리,77.9440500040,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
2,행복한약국,자양사거리,146.3385579894,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
3,금성약국,자양사거리,133.0019102985,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881
4,수약국,자양사거리,87.2256782004,127.0825836777,37.5368376735,215856,175272,18150,16434,12449,12941,9483,9944,9516,9640,7808,7887,3690,4644,1156,1096,734,692,627,528,414,420,922,844,4189,2400,5120,3881

In [ ]:
for i in add_range:
    new[f'{str(i)}시_버스_승하차승객수'] = new[f'{str(i)}시승차총승객수'] +new[f'{str(i)}시하차총승객수']

new = new.rename(columns={'X좌표': "정류장X좌표", "Y좌표": "정류장Y좌표"})
new.head()

In [202]:
new.columns

Index(['약국명', '정류소명', '최소거리', '정류장X좌표', '정류장Y좌표', '승차총승객수', '하차총승객수',
       '18시승차총승객수', '18시하차총승객수', '19시승차총승객수', '19시하차총승객수', '20시승차총승객수',
       '20시하차총승객수', '21시승차총승객수', '21시하차총승객수', '22시승차총승객수', '22시하차총승객수',
       '23시승차총승객수', '23시하차총승객수', '0시승차총승객수', '0시하차총승객수', '1시승차총승객수',
       '1시하차총승객수', '2시승차총승객수', '2시하차총승객수', '3시승차총승객수', '3시하차총승객수', '4시승차총승객수',
       '4시하차총승객수', '5시승차총승객수', '5시하차총승객수', '6시승차총승객수', '6시하차총승객수',
       '18시_버스_승하차승객수', '19시_버스_승하차승객수', '20시_버스_승하차승객수', '21시_버스_승하차승객수',
       '22시_버스_승하차승객수', '23시_버스_승하차승객수', '0시_버스_승하차승객수', '1시_버스_승하차승객수',
       '2시_버스_승하차승객수', '3시_버스_승하차승객수', '4시_버스_승하차승객수', '5시_버스_승하차승객수',
       '6시_버스_승하차승객수'],
      dtype='object')

In [203]:
new = new.drop(['18시승차총승객수', '18시하차총승객수', '19시승차총승객수', '19시하차총승객수', '20시승차총승객수',
       '20시하차총승객수', '21시승차총승객수', '21시하차총승객수', '22시승차총승객수', '22시하차총승객수',
       '23시승차총승객수', '23시하차총승객수', '0시승차총승객수', '0시하차총승객수', '1시승차총승객수',
       '1시하차총승객수', '2시승차총승객수', '2시하차총승객수', '3시승차총승객수', '3시하차총승객수', '4시승차총승객수',
       '4시하차총승객수', '5시승차총승객수', '5시하차총승객수', '6시승차총승객수', '6시하차총승객수',], axis=1)
new.head()

,약국명,정류소명,최소거리,정류장X좌표,정류장Y좌표,승차총승객수,하차총승객수,18시_버스_승하차승객수,19시_버스_승하차승객수,20시_버스_승하차승객수,21시_버스_승하차승객수,22시_버스_승하차승객수,23시_버스_승하차승객수,0시_버스_승하차승객수,1시_버스_승하차승객수,2시_버스_승하차승객수,3시_버스_승하차승객수,4시_버스_승하차승객수,5시_버스_승하차승객수,6시_버스_승하차승객수
0,더참사랑약국,자양사거리,29.5683790930,127.0825836777,37.5368376735,215856,175272,34584,25390,19427,19156,15695,8334,2252,1426,1155,834,1766,6589,9001
1,조은우리약국,자양사거리,77.9440500040,127.0825836777,37.5368376735,215856,175272,34584,25390,19427,19156,15695,8334,2252,1426,1155,834,1766,6589,9001
2,행복한약국,자양사거리,146.3385579894,127.0825836777,37.5368376735,215856,175272,34584,25390,19427,19156,15695,8334,2252,1426,1155,834,1766,6589,9001
3,금성약국,자양사거리,133.0019102985,127.0825836777,37.5368376735,215856,175272,34584,25390,19427,19156,15695,8334,2252,1426,1155,834,1766,6589,9001
4,수약국,자양사거리,87.2256782004,127.0825836777,37.5368376735,215856,175272,34584,25390,19427,19156,15695,8334,2252,1426,1155,834,1766,6589,9001

In [204]:
new.columns

Index(['약국명', '정류소명', '최소거리', '정류장X좌표', '정류장Y좌표', '승차총승객수', '하차총승객수',
       '18시_버스_승하차승객수', '19시_버스_승하차승객수', '20시_버스_승하차승객수', '21시_버스_승하차승객수',
       '22시_버스_승하차승객수', '23시_버스_승하차승객수', '0시_버스_승하차승객수', '1시_버스_승하차승객수',
       '2시_버스_승하차승객수', '3시_버스_승하차승객수', '4시_버스_승하차승객수', '5시_버스_승하차승객수',
       '6시_버스_승하차승객수'],
      dtype='object')

In [206]:
new.to_csv(path + '최종버스거리및승하차.csv')